# Build specifications for CodeBuild, used in the CI/CD process.
# buildspec.yml
# Notes:

#     Dependencies: Ensure requirements.txt contains all necessary dependencies.
#     Build Commands: Add any specific build commands that are needed for your project in the build phase.
#     Artifacts: Adjust the artifacts section based on the files you want to include in the build output.

# What’s Missing/Needed from You:

#     GitHub Repository Details: Provide the repository name and owner.
#     Build Commands: Specify any additional build commands or configurations needed.
#     Deployment Target: If not deploying to S3, let me know your target environment for adjustments.


version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Preparing for build...
  build:
    commands:
      - echo Building the project...
      - # Add your build commands here
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
