[package]
name = "aleph_research"
version = "0.1.0"
authors = ["Eric Webb <webberic92@yahoo.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ring = "0.17.8"
toml = "0.8.19"
reed-solomon-erasure = "6.0.0"
reqwest = { version = "0.12.9", features = ["json"] }
openssl = { version = "0.10", features = ["vendored"] }
axum = { version = "0.7.9", features = ["http1", "http2"] }
sha2 = "0.10"
chrono = "0.4"
base64 = "0.22.0"
futures = "0.3.30"
anyhow = "1.0.40"
tower-http = { version = "0.6.1", features = ["limit"] }
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
rand = "0.8"
num-integer = "0.1"
hex = "0.4"
rayon = "1.7.0"

[dev-dependencies]
# mockito = "1.6.1"
tokio-test = "0.4"
mockito = "0.30"

[[bin]]
name = "aleph_rbc"
path = "src/aleph_rbc.rs"
