INSERT INTO experiment_summary 
(protocol, filename, nodes, txpb, rounds, avg_tps, avg_overhead, avg_cpu, avg_mem, latency_seconds)
VALUES ('MERKLE', '104nodes_5txpb_4rounds_MERK.txt', 104, 5, 4, 
5.0, 
1638.69,
11.6,
12.16,
86.979
);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-1', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-10', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-100', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-101', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-102', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-103', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-104', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-11', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-12', 0.36);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-13', 0.36);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-14', 0.31);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-15', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-16', 0.32);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-17', 0.32);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-18', 0.36);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-19', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-2', 0.32);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-20', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-21', 0.32);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-22', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-23', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-24', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-25', 0.37);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-26', 0.37);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-27', 0.37);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-28', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-29', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-3', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-30', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-31', 0.37);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-32', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-33', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-34', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-35', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-36', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-37', 0.36);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-38', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-39', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-4', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-40', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-41', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-42', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-43', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-44', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-45', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-46', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-47', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-48', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-49', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-5', 0.37);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-50', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-51', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-52', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-53', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-54', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-55', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-56', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-57', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-58', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-59', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-6', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-60', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-61', 0.31);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-62', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-63', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-64', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-65', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-66', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-67', 0.36);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-68', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-69', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-7', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-70', 0.36);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-71', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-72', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-73', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-74', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-75', 0.36);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-76', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-77', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-78', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-79', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-8', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-80', 0.35);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-81', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-82', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-83', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-84', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-85', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-86', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-87', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-88', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-89', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-9', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-90', 0.37);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-91', 0.32);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-92', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-93', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-94', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-95', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-96', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-97', 0.34);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-98', 0.33);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (1, 'node-99', 0.33);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-1', 1545);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-10', 1575);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-100', 1749);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-101', 1720);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-102', 1556);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-103', 1608);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-104', 1533);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-11', 1697);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-12', 1545);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-13', 1702);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-14', 1775);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-15', 1691);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-16', 1499);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-17', 1632);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-18', 1597);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-19', 1718);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-2', 1518);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-20', 1738);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-21', 1595);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-22', 1743);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-23', 1748);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-24', 1736);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-25', 1696);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-26', 1643);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-27', 1538);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-28', 1643);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-29', 1631);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-3', 1641);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-30', 1612);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-31', 1635);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-32', 1738);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-33', 1697);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-34', 1645);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-35', 1574);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-36', 1697);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-37', 1448);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-38', 1599);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-39', 1575);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-4', 1759);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-40', 1756);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-41', 1510);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-42', 1575);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-43', 1484);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-44', 1541);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-45', 1693);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-46', 1709);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-47', 1777);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-48', 1717);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-49', 1592);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-5', 1649);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-50', 1767);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-51', 1728);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-52', 1712);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-53', 1632);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-54', 1590);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-55', 1448);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-56', 1714);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-57', 1751);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-58', 1760);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-59', 1591);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-6', 1716);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-60', 1582);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-61', 1665);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-62', 1382);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-63', 1362);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-64', 1561);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-65', 1653);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-66', 1600);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-67', 1671);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-68', 1711);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-69', 1728);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-7', 1772);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-70', 1629);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-71', 1610);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-72', 1752);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-73', 1715);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-74', 1761);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-75', 1490);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-76', 1489);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-77', 1545);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-78', 1739);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-79', 1753);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-8', 1775);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-80', 1673);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-81', 1754);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-82', 1729);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-83', 1569);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-84', 1758);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-85', 1516);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-86', 1556);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-87', 1737);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-88', 1773);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-89', 1518);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-9', 1529);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-90', 1589);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-91', 1796);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-92', 1623);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-93', 1489);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-94', 1518);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-95', 1697);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-96', 1605);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-97', 1614);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-98', 1607);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (1, 'node-99', 1426);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-1', 10.14, 11.77);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-10', 10.12, 12.03);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-100', 9.37, 11.99);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-101', 10.81, 11.84);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-102', 11.70, 12.08);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-103', 10.83, 11.62);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-104', 10.86, 11.78);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-11', 9.96, 11.91);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-12', 11.67, 12.09);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-13', 10.59, 12.00);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-14', 10.44, 12.15);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-15', 12.47, 12.17);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-16', 12.14, 12.28);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-17', 11.47, 12.42);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-18', 12.70, 12.25);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-19', 9.99, 12.33);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-2', 14.45, 12.77);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-20', 10.38, 11.94);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-21', 12.03, 12.14);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-22', 10.17, 11.91);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-23', 10.53, 12.48);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-24', 11.03, 12.02);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-25', 10.63, 12.12);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-26', 14.74, 12.75);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-27', 12.76, 12.58);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-28', 14.20, 12.51);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-29', 14.94, 12.46);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-3', 11.24, 11.88);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-30', 13.11, 12.24);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-31', 12.51, 12.14);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-32', 11.91, 12.05);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-33', 9.83, 12.29);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-34', 12.98, 12.00);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-35', 11.67, 12.14);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-36', 10.55, 12.12);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-37', 10.92, 12.29);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-38', 10.63, 11.72);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-39', 10.42, 12.02);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-4', 10.99, 12.24);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-40', 10.54, 12.05);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-41', 12.66, 12.10);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-42', 12.22, 12.23);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-43', 11.41, 12.17);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-44', 11.28, 11.94);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-45', 13.65, 12.10);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-46', 10.86, 11.98);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-47', 10.45, 11.93);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-48', 14.00, 12.44);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-49', 11.61, 11.98);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-5', 11.78, 12.26);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-50', 10.81, 11.90);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-51', 10.49, 12.13);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-52', 12.29, 12.04);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-53', 11.81, 12.53);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-54', 14.47, 12.25);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-55', 10.43, 12.22);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-56', 12.57, 12.22);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-57', 11.87, 12.31);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-58', 11.41, 12.37);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-59', 11.56, 12.47);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-6', 10.08, 11.96);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-60', 11.84, 11.72);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-61', 11.49, 12.13);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-62', 11.50, 11.74);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-63', 14.60, 12.44);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-64', 11.06, 12.03);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-65', 11.33, 12.44);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-66', 10.53, 11.92);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-67', 14.00, 12.61);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-68', 13.21, 12.43);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-69', 10.80, 11.91);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-7', 12.54, 12.24);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-70', 11.15, 12.37);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-71', 10.94, 11.95);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-72', 13.28, 12.37);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-73', 10.37, 11.76);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-74', 10.82, 12.18);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-75', 11.35, 12.24);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-76', 12.99, 12.66);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-77', 10.02, 12.35);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-78', 12.14, 12.18);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-79', 9.46, 12.21);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-8', 12.62, 12.35);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-80', 11.19, 12.13);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-81', 9.37, 12.09);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-82', 10.08, 12.23);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-83', 8.77, 12.15);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-84', 9.56, 12.24);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-85', 10.48, 12.11);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-86', 10.68, 12.12);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-87', 10.17, 12.16);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-88', 12.90, 12.11);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-89', 10.01, 12.01);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-9', 11.21, 12.10);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-90', 11.39, 12.08);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-91', 19.70, 13.23);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-92', 12.34, 12.22);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-93', 13.69, 12.45);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-94', 13.51, 11.72);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-95', 13.28, 12.37);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-96', 11.40, 12.19);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-97', 11.70, 12.14);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-98', 10.01, 12.30);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (1, 'node-99', 11.25, 12.18);
INSERT INTO experiment_summary 
(protocol, filename, nodes, txpb, rounds, avg_tps, avg_overhead, avg_cpu, avg_mem, latency_seconds)
VALUES ('MERKLE', '64nodes_25txpb_25rounds_MERK.txt', 64, 25, 25, 
25.0, 
5523.42,
21.68,
13.85,
776.14
);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-1', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-10', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-11', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-12', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-13', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-14', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-15', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-16', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-17', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-18', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-19', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-2', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-20', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-21', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-22', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-23', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-24', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-25', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-26', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-27', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-28', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-29', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-3', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-30', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-31', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-32', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-33', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-34', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-35', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-36', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-37', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-38', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-39', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-4', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-40', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-41', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-42', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-43', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-44', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-45', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-46', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-47', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-48', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-49', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-5', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-50', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-51', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-52', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-53', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-54', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-55', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-56', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-57', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-58', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-59', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-6', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-60', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-61', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-62', 0.84);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-63', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-64', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-7', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-8', 0.85);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (2, 'node-9', 0.85);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-1', 5605);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-10', 5577);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-11', 5465);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-12', 5735);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-13', 5556);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-14', 5642);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-15', 5523);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-16', 5512);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-17', 5572);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-18', 5577);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-19', 4081);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-2', 5599);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-20', 5457);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-21', 5489);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-22', 5488);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-23', 5669);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-24', 5677);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-25', 5506);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-26', 5540);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-27', 5489);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-28', 5328);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-29', 5695);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-3', 5674);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-30', 5491);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-31', 5654);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-32', 5446);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-33', 5602);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-34', 5680);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-35', 5534);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-36', 5510);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-37', 5646);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-38', 5357);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-39', 5592);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-4', 5385);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-40', 5572);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-41', 5506);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-42', 5552);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-43', 5482);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-44', 5484);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-45', 5637);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-46', 5542);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-47', 5556);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-48', 5587);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-49', 5516);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-5', 5650);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-50', 5438);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-51', 5671);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-52', 5617);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-53', 5428);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-54', 5616);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-55', 5455);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-56', 5574);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-57', 5493);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-58', 5508);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-59', 5694);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-6', 5594);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-60', 5497);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-61', 5486);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-62', 5608);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-63', 5403);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-64', 5403);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-7', 5568);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-8', 5472);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (2, 'node-9', 5537);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-1', 20.93, 13.85);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-10', 20.56, 14.01);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-11', 20.89, 13.80);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-12', 22.35, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-13', 21.43, 13.80);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-14', 21.37, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-15', 21.28, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-16', 22.81, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-17', 21.24, 13.77);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-18', 21.12, 13.96);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-19', 27.17, 13.89);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-2', 21.67, 13.91);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-20', 21.49, 14.00);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-21', 20.81, 13.85);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-22', 21.46, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-23', 21.30, 13.85);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-24', 22.37, 14.00);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-25', 20.77, 13.92);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-26', 21.12, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-27', 20.68, 13.84);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-28', 23.99, 13.81);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-29', 23.87, 13.76);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-3', 21.70, 13.82);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-30', 22.30, 13.95);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-31', 21.17, 13.75);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-32', 23.09, 13.94);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-33', 22.15, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-34', 21.09, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-35', 21.13, 14.09);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-36', 21.25, 13.78);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-37', 21.26, 13.67);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-38', 21.07, 13.76);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-39', 21.18, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-4', 21.93, 13.78);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-40', 22.66, 13.85);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-41', 21.55, 13.83);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-42', 22.38, 13.89);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-43', 20.52, 13.94);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-44', 21.35, 13.94);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-45', 23.38, 13.71);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-46', 20.33, 13.90);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-47', 20.92, 13.98);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-48', 21.32, 13.72);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-49', 21.07, 13.81);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-5', 21.19, 13.73);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-50', 20.85, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-51', 21.06, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-52', 20.56, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-53', 22.36, 13.98);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-54', 20.63, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-55', 21.90, 13.92);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-56', 23.30, 13.78);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-57', 21.66, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-58', 22.59, 13.97);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-59', 21.27, 13.78);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-6', 20.91, 13.85);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-60', 21.55, 13.86);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-61', 22.60, 13.83);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-62', 22.05, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-63', 21.71, 13.92);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-64', 21.26, 13.96);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-7', 21.52, 13.88);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-8', 21.37, 13.83);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (2, 'node-9', 21.75, 13.84);
INSERT INTO experiment_summary 
(protocol, filename, nodes, txpb, rounds, avg_tps, avg_overhead, avg_cpu, avg_mem, latency_seconds)
VALUES ('RSA', '104nodes_5txpb_4rounds_RSA.txt', 104, 5, 4, 
5.0, 
1908.59,
16.52,
13.99,
428.528
);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-1', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-10', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-100', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-101', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-102', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-103', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-104', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-11', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-12', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-14', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-15', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-16', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-17', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-18', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-19', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-20', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-23', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-24', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-25', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-26', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-27', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-28', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-29', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-3', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-30', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-31', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-32', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-33', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-34', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-35', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-36', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-37', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-38', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-39', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-4', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-40', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-42', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-44', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-45', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-46', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-49', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-5', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-50', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-51', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-52', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-53', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-54', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-56', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-57', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-58', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-59', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-6', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-60', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-61', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-62', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-63', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-64', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-65', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-66', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-67', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-68', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-69', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-7', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-70', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-72', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-73', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-74', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-75', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-76', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-78', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-8', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-81', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-85', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-86', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-87', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-88', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-90', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-91', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-93', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-94', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-95', 0.06);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-96', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-97', 0.07);
INSERT INTO node_tps (experiment_id, node_id, tps) VALUES (3, 'node-99', 0.06);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-1', 2190);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-10', 2001);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-100', 2000);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-101', 2251);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-102', 2249);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-103', 1970);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-104', 2230);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-11', 1757);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-12', 1661);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-14', 1849);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-15', 1750);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-16', 1881);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-17', 1884);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-18', 1837);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-19', 2089);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-20', 1865);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-23', 1901);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-24', 2046);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-25', 1837);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-26', 1939);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-27', 1636);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-28', 2040);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-29', 1869);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-3', 2228);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-30', 1791);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-31', 1986);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-32', 2060);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-33', 1742);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-34', 2010);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-35', 1887);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-36', 1820);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-37', 1656);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-38', 1875);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-39', 1714);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-4', 1917);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-40', 1799);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-42', 2117);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-44', 1987);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-45', 2174);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-46', 1995);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-49', 2165);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-5', 1777);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-50', 1979);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-51', 1652);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-52', 1808);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-53', 2050);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-54', 1818);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-56', 1510);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-57', 1632);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-58', 1776);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-59', 1891);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-6', 2020);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-60', 1921);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-61', 1650);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-62', 1732);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-63', 1934);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-64', 1544);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-65', 2041);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-66', 2023);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-67', 2024);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-68', 2136);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-69', 1893);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-7', 1693);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-70', 1799);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-72', 2073);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-73', 1722);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-74', 1605);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-75', 2129);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-76', 1820);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-78', 1781);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-8', 1996);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-81', 1815);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-85', 1504);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-86', 1825);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-87', 1693);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-88', 1819);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-90', 2086);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-91', 2092);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-93', 1898);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-94', 2115);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-95', 2277);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-96', 2118);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-97', 2140);
INSERT INTO node_overhead (experiment_id, node_id, overhead_messages) VALUES (3, 'node-99', 1856);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-1', 16.26, 13.48);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-10', 16.06, 14.27);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-100', 14.33, 14.08);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-101', 15.94, 13.60);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-102', 17.40, 14.22);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-103', 16.76, 13.95);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-104', 14.02, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-11', 14.82, 13.96);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-12', 19.19, 14.07);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-14', 15.13, 14.07);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-15', 19.61, 14.17);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-16', 17.73, 13.75);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-17', 14.46, 13.77);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-18', 18.81, 13.94);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-19', 14.78, 13.93);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-20', 14.21, 13.82);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-23', 15.19, 14.23);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-24', 15.08, 13.65);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-25', 15.99, 14.33);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-26', 15.81, 13.98);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-27', 22.35, 14.17);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-28', 14.21, 13.90);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-29', 21.06, 14.02);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-3', 16.58, 14.04);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-30', 18.94, 14.01);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-31', 16.19, 14.16);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-32', 17.40, 14.14);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-33', 19.51, 14.46);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-34', 16.07, 13.65);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-35', 14.88, 14.45);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-36', 14.69, 13.63);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-37', 15.54, 13.54);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-38', 18.33, 14.19);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-39', 15.20, 14.04);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-4', 15.25, 13.85);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-40', 18.01, 14.00);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-42', 15.63, 13.71);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-44', 16.22, 13.90);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-45', 14.52, 13.89);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-46', 13.89, 13.54);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-49', 15.61, 13.93);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-5', 14.80, 13.89);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-50', 18.78, 13.88);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-51', 16.60, 14.33);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-52', 19.08, 14.52);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-53', 15.65, 13.95);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-54', 14.60, 14.18);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-56', 21.88, 14.19);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-57', 17.97, 14.41);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-58', 14.41, 14.32);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-59', 18.79, 14.19);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-6', 15.08, 13.74);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-60', 15.31, 14.46);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-61', 17.30, 14.28);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-62', 15.47, 13.80);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-63', 16.45, 14.12);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-64', 19.24, 14.00);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-65', 14.61, 13.81);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-66', 16.88, 14.32);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-67', 16.06, 14.19);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-68', 19.87, 14.09);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-69', 14.67, 13.98);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-7', 15.28, 13.90);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-70', 20.03, 13.84);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-72', 17.72, 13.79);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-73', 16.10, 14.32);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-74', 19.13, 13.78);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-75', 15.28, 13.99);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-76', 15.18, 13.98);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-78', 15.72, 14.83);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-8', 15.37, 13.86);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-81', 17.86, 14.12);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-85', 16.71, 14.45);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-86', 14.17, 13.95);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-87', 17.32, 14.27);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-88', 15.91, 14.19);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-90', 14.37, 13.83);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-91', 16.12, 13.78);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-93', 19.67, 13.83);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-94', 15.96, 13.87);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-95', 15.96, 13.32);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-96', 18.57, 13.68);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-97', 15.18, 13.63);
INSERT INTO node_resource_utilization (experiment_id, node_id, cpu_util, mem_util) VALUES (3, 'node-99', 15.63, 13.65);