
            [network]
            listen_address = "127.0.0.1"
            nodes = ["http://node1.local", "http://node2.local"]
            ip_manager_address = "http://ip_manager.local"
            proposals = [1, 2, 3]
            ip_address = "127.0.0.1"
    
            [consensus]
            transaction_size = 256
            data_shards = 4
            batch_size = 10
            epoch_round_id = 1
    
            [node]
            id = 1
            total_nodes = 3
        