[package]
name = "aleph-orig"
version = "0.1.0"
authors = ["Eric Webb webberic92@yahoo.com"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
postgres = "0.19"
